# Generated by Django 4.2.2 on 2023-07-03 03:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0002_qapost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qapost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
